[project]
name = "sqlagent"
version = "0.1.0"
description = "A PoC showing how to create a SQL agent using smolagents"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "duckdb>=1.3.0",
    "pandas>=2.2.3",
    "smolagents[openai]>=1.17.0",
]
